language: ruby
rvm:
- 2.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --external_only --only-4xx --check-favicon --check-html --verbose

branches:
  only:
  - gh-pages
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    on_success: never
    on_failure: always
