# build settings
permalink: /blog/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

paginate: 4
paginate_path: "/blog/page/:num/"
comments: true

source: .
destination: _site
sass:
  sass_dir: _scss
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji # http://www.emoji-cheat-sheet.com/

# seo settings
title: "Goran Gligorin"
description: "A free Jekyll theme for download"
keywords: "goran gligorin, goran, gligorin, blog, cv, curriculum vitae, developer, web developer, c# developer, .net developer, entrepreneur"
url: http://gorangligorin.com
baseurl: ""

google_analytics: UA-9914927-3
repo: http://github.com/gligoran/gorangligorin.com
disqus_shortname: "gorangligorin"
disqus_site_shortname: "gorangligorin"

# author settings
author:
  name: Goran Gligorin
  job: C# & Web Developer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  gravatar: https://2.gravatar.com/avatar/9779eebf2a998acf07d40665c0dbbaf3
  thumb: /images/gorangligorin.png
  email: goran@gligorin.com
  url: http://gorangligorin.com
  github: http://github.com/gligoran
  twitter: http://twitter.com/gligoran
  facebook: http://facebook.com/goran.gligorin
  linkedin: http://linkedin.com/in/gorangligorin

# nav pages
nav:
  - slug: blog
    title: blog
  - slug: skills
    title: skills
  - slug: work-experience
    title: work experience
  - slug: projects
    title: projects
  - slug: education
    title: education
  - slug: archives
    title: archives

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
