# build settings
permalink: /blog/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

paginate: 4
paginate_path: "/blog/page/:num/"
comments: true

source: .
destination: _site
sass:
  style: compressed

post_ext: md
page_ext: md

plugins:
  - github-pages
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji # https://www.emoji-cheat-sheet.com/

exclude:
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - .remarkrc
  - vendor
  - README.md
  - CNAME

# seo settings
title: "Goran Gligorin"
description: "Goran Gligorin's little piece of the Internet"
keywords: "goran gligorin, goran, gligorin, blog, cv, curriculum vitae, developer, web developer, c# developer, .net developer, entrepreneur"
url: https://www.gorangligorin.com
baseurl: ""

google_analytics_tracking_id: UA-9914927-3
# repo: https://github.com/gligoran/gorangligorin.com
disqus_short_name: "gorangligorin"
disqus_show_comment_count: true

# author settings
author:
  name: Goran Gligorin
  ima: "c# programmer, web developer, internet marketer, online entrepreneur, go-kart racer &amp; runner"
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  # image: https://2.gravatar.com/avatar/9779eebf2a998acf07d40665c0dbbaf3?s=240
  image: /images/gorangligorin-bw.png
  birthdate: 1986-09-24
  email: goran@gligorin.com
  url: https://www.gorangligorin.com
  github: gligoran
  twitter: gligoran
  facebook: goran.gligorin
  linkedin: gorangligorin
