# build settings
permalink: /blog/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

paginate: 2
paginate_path: "/blog/page/:num/"
comments: true

source: .
destination: _site
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji # http://www.emoji-cheat-sheet.com/

exclude:
  - node_modules
  - package.json
  - bower_components
  - bower.json
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - .remarkrc

# seo settings
title: "Goran Gligorin"
description: "Goran Gligorin's little piece of the Internet"
keywords: "goran gligorin, goran, gligorin, blog, cv, curriculum vitae, developer, web developer, c# developer, .net developer, entrepreneur"
url: http://gorangligorin.com
baseurl: ""

google_analytics_tracking_id: UA-9914927-3
# repo: http://github.com/gligoran/gorangligorin.com
disqus_short_name: "gorangligorin"
disqus_show_comment_count: true

# author settings
author:
  name: Goran Gligorin
  ima: "c# programmer, web developer, internet marketer, online entrepreneur & go-kart racer"
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  # image: https://2.gravatar.com/avatar/9779eebf2a998acf07d40665c0dbbaf3?s=240
  image: /images/gorangligorin-bw.png
  email: goran@gligorin.com
  url: http://gorangligorin.com
  github: http://github.com/gligoran
  twitter: http://twitter.com/gligoran
  facebook: http://facebook.com/goran.gligorin
  linkedin: http://linkedin.com/in/gorangligorin
