name = "gorangligorin"
type = "webpack"
account_id = "cb7d4a209e211ccf250880761e0e9b7b"
workers_dev = false
route = "https://www.gorangligorin.com/*"
zone_id = "2eee291132e097327b6a7481017a04da"

[site]
bucket = "./_site"
entry-point = "workers-site"
exclude = ["workers-site", "wrangler.toml", "renovate.json", "redirects.json", "package.json", "package-lock.json"]
