name: auto-merge

on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4.0
        with:
          target: minor
          command: squash and merge
          github-token: ${{ secrets.GH_PAT }}
