name: cloudflare

on: push

jobs:
  build-and-deploy:
    name: build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install gems
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: build jekyll
        run: bundle exec jekyll build

      - name: check links
        run: bundle exec htmlproofer --external-only --only-4xx --check-favicon --check-html --url-ignore "https://kit.fontawesome.com/fe53b9ab7d.js" ./_site

      - name: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
